### ISSUE TITLE
CASE TRANSFER: split and enhance

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#460]
So, we are going to take the ACTIONS - CASE TRANSFER and create two scripts:

- [ ] An ACTIONS script which contains the single-case functionality currently implemented.
- [ ] A BULK script which contains the current multi-case functionality, with the added benefit of allowing for multiple conditions to determine which case to transfer.

My splitting them, agencies could block access to BULK functionality from folks who shouldn't be able to see it. @khiestand has volunteered to take this on, because she's a rock star.

**Comment by khiestand** [comment]
Update-
I have pulled in the ACTIONS - Case transfer script as a stand alone actions script.
I have noticed that there are bugs in the Bulk Case Transfer scripts, and added an issued on the issue list for Robert to take a look as he was the script writer of that one.  If Robert cannot do this in the next two days, Veronica will pull the script.  The Actions - Case Transfer script button already exists so that should be good to go.

**Comment by theVKC** [comment]
#527 addresses the bug. I will clear the bulk script in a couple days if I don't hear from @RobertFewins-Kalb. Robert, if you can pull in the working bulk portion as a new bulk script, that'd be superb. :)

**Comment by RobertFewins-Kalb** [comment]
Pull 308 (https://github.com/MN-Script-Team/DHS-PRISM-Scripts/pull/308/files) shows what needs to be separated to make the one script into two. The bulk part worked just fine on Friday at 3:45 PM when I was asked to help someone do it.

I am unable to log in to my GH account on accounta I accidentally deleted my authenticator app while on vacation because of my whimsy and now I don’t know where my recovery code is so that’s a thing that’s happening right now…

Just about to throw my hands up and create a new account.


NOTICE: Unless restricted by law, email correspondence to and from Anoka County government offices may be public data subject to the Minnesota Data Practices Act and/or may be disclosed to third parties.

**Comment by theVKC** [comment]
Just a note: @RoberT-1000 has agreed to put this into SIR instructions (reorganizing issues and instructions tracking).

**Comment by theVKC** [comment]
OK, I am moving this issue to "completed" because instructions are made and published. Thanks @RoberT-1000! 

@khiestand: your issue #628 will also need to be documented in your instructions you're working on, so I will assign that one to you, and I'll stop commenting here. :)
