### ISSUE TITLE
IW CAAD CAWT: add IW CALC features and more from Anoka

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#473]
Anoka made a custom version of this, and I've asked @levesswe to add their features to this script to provide state support. She can describe the details of what it does better than I can.

Thanks Wendy!!!!

**Comment by levesswe** [comment]
Veronica, the updated script is better described as an ACTIONS script rather than a NOTES script.  Wondering if it makes more sense to simply add it to ACTIONS as a new script rather than use this file name/category that is inaccurate for the updated script.

The script pulls in the employer name, current obligation, nonaccrual (if there is one), and has a check box for adding the additional 20%.  There are checkboxes for adding a 30 day worklist to check if payments are received, and for entering a CAAD note about the IW that went out (both selected by default, because that is how Anoka supervisors want it).  If you uncheck both the worklist and CAAD note checkboxes, the IW information displays in a message box. For all three output options, the end result includes the expected payment amounts for the monthly, biweekly, semi-monthly, and weekly pay frequencies.

**Comment by theVKC** [comment]
I think making it a new ACTIONS script and retiring the old is a great idea. Make it so, @levesswe!
