### ISSUE TITLE
BUG: beta users scripts' functions library call

### ISSUE THREAD

**Issue by levesswe** [MN-Script-Team/DHS-PRISM-Scripts#498]
Beta users have reported that they are not able to access scripts and they receive an error message that the code in GitHub is not able to be reached.  

The functions library call needs to be updated for the scripts on the beta branch.

**Comment by theVKC** [comment]
Do you mean "beta branch" users?

If folks using the beta branch are having difficulty, a simple solution is to move them to master (as we are abandoning the beta branch anyway). If by "beta users" you mean master branch users, we've got master branch users in other counties accessing scripts without issue.

If it's beta-branch users with the problem, it's likely that your global variables are not setting beta_branch rules correctly. For example, if you're a beta branch user but the scripts think you're a master branch user, then it connects with the old master Shared Functions Library (which no longer exists). If that's the case, your global variables file needs to include handling to point users in the proper direction.

In the old Shared Functions Library block, note the `beta_agency = true` logic:

```vb.net
'LOADING ROUTINE FUNCTIONS (FOR PRISM)---------------------------------------------------------------
Dim URL, REQ, FSO					'Declares variables to be good to option explicit users
If beta_agency = "" then 			'For scriptwriters only
	url = "https://raw.githubusercontent.com/MN-CS-Script-Team/PRISM-Scripts/master/Shared%20Functions%20Library/PRISM%20Functions%20Library.vbs"
ElseIf beta_agency = True then		'For beta agencies and testers
	url = "https://raw.githubusercontent.com/MN-CS-Script-Team/PRISM-Scripts/beta/Shared%20Functions%20Library/PRISM%20Functions%20Library.vbs"
Else								'For most users
	url = "https://raw.githubusercontent.com/MN-CS-Script-Team/PRISM-Scripts/release/Shared%20Functions%20Library/PRISM%20Functions%20Library.vbs"
End if
```

If this logic is missing or otherwise being reset, that explains the issue (and should be repairable using your global variables file without affecting other scripts).

In any case, I am closing this issue because we're abandoning the beta branch, and there is a simple workaround to allow agencies to continue using it if desired. @gretchent74, I believe you might be experiencing a similar issue. 

If you are unable to fix it, and unable to switch everyone to master branch (at least temporarily while we await the new installer), then let me know via email or Slack and I'll touch base.
