### ISSUE TITLE
ACTIONS Non Pay -- issue with last payment amount on the dord document

### ISSUE THREAD

**Issue by gretchent74** [MN-Script-Team/DHS-PRISM-Scripts#569]
The last payment amount on prism was $4,767.00 but the script put $,767.00 in the dord document.  Has anyone else had this problem?

**Comment by theVKC** [comment]
I'm going to take a guess and say the scriptwriter didn't anticipate commas.

@KallistaImdieke, sound familiar? I believe we dealt with a similar issue yesterday. Care to enlighten us with your solution that you used yesterday?

**Comment by KallistaImdieke** [comment]
@gretchent74  @theVKC  

I reviewed the code on this case and it appears that this may be happening because we are only reading at row 7, column 53 on PAPL which only allows for 4 numbers before the decimal point XXXX.XX ( and this number is longer that that with the Comma that the system puts in.  I believe that if we would need to change the script to pull from row 7, column 50 or 51 and this will correct this issue.

**Comment by theVKC** [comment]
@KallistaImdieke, would you want to take on this issue?

**Comment by KallistaImdieke** [comment]
Yes I can take it

**Comment by theVKC** [comment]
Excellent. Thank you!!
