### ISSUE TITLE
Note: Client Contact Error Message

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-Script-Team/DHS-PRISM-Scripts#574]
I have received emails that the following issues is popping up after the client contact script is ran. 

![capture](https://cloud.githubusercontent.com/assets/19214103/19354234/ab609866-912b-11e6-9789-5e4f133f2b4b.PNG)

Any ideas what may be causing this?

Thanks!

**Comment by theVKC** [comment]
This looks like an internal issue. Anytime you see the H:\ (or any Stearns-specific drive being referenced) it's likely an internal issue that's causing the problem. In this case, it looks like your database is missing, too full, or perhaps it's being queried. I'd bet @GayS would have ideas on what to do next.

Also, @IlseFerris, does this look like the infamous Hennepin database bug that you've seen so many times?

**Comment by theVKC** [comment]
Also, if Gay isn't able to help resolve, let me know and I can try and walk you through some scenarios. Hoping Ilse's experience in Hennepin also comes in handy here (they have seen more database issues than anyone due to volume).

**Comment by IlseFerris** [comment]
Oh I know this error well :)
This is the infamous database error. The database may need a repair run, or it's in read-only status so that data is not able to be written to it. 

The error shouldn't be inhibiting your users from using scripts (they will just need to close the error message), but data won't be collected about script usage while the database is not accessible.

**Comment by theVKC** [comment]
If it's super duper annoying, you can temporarily disable the stats variable in Global Variables.

**Comment by GayS** [comment]
Thanks for the info – yes the database needed repair! ☺
