### ISSUE TITLE
County Word Document script

### ISSUE THREAD

**Issue by TammyStearns** [MN-Script-Team/DHS-PRISM-Scripts#651]
This would be similar to the DHS-SIR, SIR-MILO Common Links power pad.  By selecting this power button, you will have the option to choose what Word Document you are wanting to use and the document will pull up from wherever they are saved in the County.  

This will save time from searching for the document in the area that the Counties save them to.  Counties may need to rename the WORD documents to be the same/similar in order for this to work.

**Comment by theVKC** [comment]
I was hoping to get feedback on this one, but haven't had any yet. @MN-Script-Team/prism-scriptwriters and @MN-Script-Team/prism-supervisors, can I get some feedback on this? If I don't receive feedback this week, I'll be closing the issue December 5th for lack of interest.

**Comment by jannellstearns** [comment]
This sounds like an efficient tool for counties to use.  I could see this having applicability in a script like the intake script that is being worked on.  many counties have specific word documents that have been vetted and approved by their County Attorney's office

**Comment by theVKC** [comment]
From an administrator standpoint, I worry that it would be a challenge to provide independent support for it across lots of counties with lots of different tech experience and server setups. If I provide it, I need to be able to ensure it works in the majority of counties, and I worry about this one because of the complexity with all of their different server settings.

But, perhaps it's just SO VERY HELPFUL that it deserves the attention from me. I don't know. If I could get more feedback, that'd be super helpful for me making my decision.

(And of course, nothing stops Stearns from doing this as an Agency Custom script, since you only have to support your people that way)

**Comment by wrightcountykaren** [comment]
I think this sounds like a very useful tool that would benefit many counties.  There are many different processes that lead to generating a Word document.
