### ISSUE TITLE
External Resources - Add a "Add New" button?

### ISSUE THREAD

**Issue by heatherallen** [MN-Script-Team/DHS-PRISM-Scripts#665]
Is there a way to add a "Add New" button? When we click on the external resources button it shows the ones I have added but to get to add a new one i have to click the "cancel" button, which then asks me "Are you sure you want to cancel the script? Press YES to cancel or Press NO to return to script" where I have to click "No", then it brings me the Manage Resources dialog to add new link.

**Comment by RoberT-1000** [comment]
Are you talking about this?

![image](https://cloud.githubusercontent.com/assets/22157633/20568579/9ab984da-b162-11e6-8add-abbb59a19ce4.png)
![image](https://cloud.githubusercontent.com/assets/22157633/20568620/b2b2103e-b162-11e6-863f-cbf17fa1f46a.png)

**Comment by heatherallen** [comment]
I don't see that when that dialog opens up. I don't see any of that Admins Only box, to update or delete either.

**Comment by RoberT-1000** [comment]
You need to be added to the `beta_users` group in GlobVar

**Comment by theVKC** [comment]
@RoberT-1000: perhaps we should provide another mechanism (er, global variable) for users for this? Long term, most counties will NOT want to give their users master branch access (`beta_users` get this) but may still want to provide users for this. Or alternatively, if `beta_users` has no users, perhaps it could give this to everyone?

In any case, @heatherallen, were you able to get to this from another screen? Because that's what I'm hearing, and if a non-`beta_user` can get to this somehow, perhaps there's a logic flaw somewhere...

**Comment by RoberT-1000** [comment]
I can dig into this next week.

**Comment by theVKC** [comment]
Good deal. Thank you!
