### ISSUE TITLE
Return Mail Script - Does not work on closed cases

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-Script-Team/DHS-PRISM-Scripts#734]
I have been told by the people running the Return mail script that it has not worked on closed cases.  has anyone else run into this issue or know why this would be?  

Thanks!!

**Comment by khiestand** [comment]
I have no idea why this wouldn't work on a closed case, @levesswe would you want to take a peek since you helped me write it??

**Comment by KallistaImdieke** [comment]
It was weird because after the script errored out they were able to update it manually so I am unsure of why it did not work.

**Comment by levesswe** [comment]
In reviewing the code, on line 166 we are calling the PRISM-case_number_finder function with the variable of PRISM_case_number_to_check, but we are missing an EMReadScreen before line 166 to determine what the value of PRISM_case_number_to_check is.  Since PRISM_case_number_to_check is undefined, the if statement is false most of the time when there is a case in the globals.  If there isn't a case in the globals, the blank case number equals the blank variable, and the script is not able to navigate to the case, and error messages ensue.  It actually has nothing to do with the case status.  @khiestand, want to try fixing the problem?

**Comment by theVKC** [comment]
@levesswe thinks this is a quick fix and has volunteered. Thank you!

**Comment by theVKC** [comment]
Can you test this, @KallistaImdieke? I just pulled in @levesswe's fix in master.

**Comment by theVKC** [comment]
This was pulled in and is working.
