### ISSUE TITLE
New Script - F0460 CP Parent Locate Questionnaire   

### ISSUE THREAD

**Issue by jlmartinone** [MN-Script-Team/DHS-PRISM-Scripts#777]
Send the CP DORD F0460, modifies CAAD to include date sent and if it is 1st, 2nd or 3rd time sent.  Puts a worklist out there when sending the 3rd request for CP to be called. 

Please assign this to me!

**Comment by KyleNelson-Hennepin** [comment]
Shouldn't workers call the CP before sending the F0460, and only send the F0460 if they're not able to reach the CP by phone? Or do you send the F0460 a few times before calling the CP?

**Comment by jlmartinone** [comment]
This was based on some feedback from a few counties but defiantly needs work.  I would love any input.

In order to CLOSE the case for CP non-coop (927) policy states CP did not respond to “several” phone attempts.

Another suggestion that was made was that if the CP does not respond to the 1st request, that when a 2nd  request is made a MEMO is included, with statements about CP’s requirements to return the documents, even if they have no new info. Also stating that the case can close if they do not respond.

Please send any feedback or ideas!

Thanks

[Wright County, Minnesota]
[Wright County on Twitter]<https://twitter.com/WrightCountyMN>  [Wright County on LinkedIn] <https://www.linkedin.com/company/wright-county>   [Wright County Youtube] <https://www.youtube.com/channel/UC8E7I0JyNFXMDrYvMUWtZmA>



Jodi Martin • Child Support Officer
WRIGHT COUNTY, MINNESOTA: HEALTH & HUMAN SERVICES
direct: (763) 682-7439   •   fax: (763) 682-8920
Government Center, 10 2nd St. NW, Buffalo, MN 55313
www.co.wright.mn.us<http://www.co.wright.mn.us/>

**Comment by jlmartinone** [comment]
Kelly (Wright County) had her baby!

Kelly, Nate and their daughter Paige would like to announce that Spencer James Hiestand was born  at 2:33pm on Monday 4/24/17 , weighing in at 8lbs 6oz, 20.5 inches long.



[cid:image001.png@01D2C01B.521A7000]




[cid:image007.png@01D2C01C.D4397BC0]

[Wright County, Minnesota]
[Wright County on Twitter]<https://twitter.com/WrightCountyMN>  [Wright County on LinkedIn] <https://www.linkedin.com/company/wright-county>   [Wright County Youtube] <https://www.youtube.com/channel/UC8E7I0JyNFXMDrYvMUWtZmA>



Jodi Martin • Child Support Officer
WRIGHT COUNTY, MINNESOTA: HEALTH & HUMAN SERVICES
direct: (763) 682-7439   •   fax: (763) 682-8920
Government Center, 10 2nd St. NW, Buffalo, MN 55313
www.co.wright.mn.us<http://www.co.wright.mn.us/>




NOTICE: This E-mail (including attachments) is covered by the Electronic Communications Privacy Act, 18 U.S.C. 2510-2521. This E-mail may be confidential and may be legally privileged. If you are not the intended recipient, you are hereby notified that any retention, dissemination, distribution, or copying of this communication is strictly prohibited. Please reply back to the sender that you have received this message in error, then delete it. Thank you.

**Comment by paschell** [comment]
From DHS/SIR MILO “Case Closure/CP Non-Coop"

If a custodial parent (CP) is non-cooperative, use ‘Reason’ code ‘927’ - NPA/CP FAIL COOP on the Case Closure Maintenance (CACL) screen when all the following conditions exist: 
•	an action by the CP is essential for the Child Support Officer (CSO) to provide the next step in child support services
•	circumstances where the CP has not cooperated are documented, and no public assistance (PA) arrears are owed on the case, or it is a child-only medical assistance case. 
Actions required:
•	The CSO must document on the Case Activities Detail (CAAD) screen the specific information the CP failed to make available.  Documenting the lack of essential information is critical because the lack of information prevents the CSO from advancing to the next step in providing IV-D services.  Modify the ‘IV-D Cooperation Code’ field on the Good Cause Safety Concerns (GCSC) screen to ‘N’ (no) and update the ‘Effective Date’ field.
Example:   The CSO sent a request for information to the CP.  It is essential that the CP return the information or the CSO cannot take the next step in providing services.  The CP did not respond.  The CAAD screen indicates the lack of response to the request for information.  The CP did not respond to the several phone attempts from the CSO.  The CSO adds the phone attempt information to the CAAD screen.  
The CSO updates the ‘IV-D Cooperation Code’ field on GCSC screen to ‘N’.  The CSO starts the case closure process for ‘Reason’ code ‘927’ on the CACL screen. CSO starts the case closure process for ‘Reason’ code ‘927’ on the CACL screen. 

PRISM then sends out Notices based on NPA or PA status F1160 or F1165

**Comment by paschell** [comment]
Oh and congratulations to Kelli in Wright County on her bundle of JOY!!
